### ISSUE TITLE
Issue in /src/pages/guides/authentication/JWT/index.md

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/adobe-dev-console#115]
I would like to get an example curl command, with actual values and not placeholders, to see how to get the token using curl.

**Comment by theManikJindal** [comment]
Hi, we are no longer enhancing documentation for Service Account (JWT) credentials as they are deprecated. 
Here are some links that may be helpful

* [Migration to OAuth Server-to-Server credentials](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/)
* [Generating access tokens programmatically \](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation/)
