### ISSUE TITLE
Server to Server Authentication - No documentation for connected apps "Requires Adobe review" 

### ISSUE THREAD

**Issue by TRSully** [AdobeDocs/adobe-dev-console#119]
After setting up Server to Server Authentication and then clicking on "Connect another service", some services such as Lightroom, have a "Requires Adobe Review" blue box and the ability to add them is disabled. There is no documentation on how to initiate this review. (Or if its even possible)

It would be extremely beneficial to be able to use client_credentials grant type with Adobe Lightroom and not have to use web-based authentication. I don't understand why Photoshop is allowed to be connected this way, but Lightroom is not. 

I understand I can create a logon redirect, and then hold the refresh token on the server, and keep refreshing forever. But if that loses access then it forces me/the user to log back on to click some buttons.

![image](https://github.com/AdobeDocs/adobe-dev-console/assets/1843314/48c20c8f-3e3b-45c3-b662-eb435ca32e8c)

**Comment by theManikJindal** [comment]
Hi @TRSully the Lightroom Services API card does not support server to server authentication. However you can still add it to your project with a different credential. I will be sending your issue to the Lightroom team. In case they have something planned, they will reach out to you.
