### ISSUE TITLE
404 from link

### ISSUE THREAD

**Issue by kultgenj** [AdobeDocs/adobe-dev-console#12]
Issue in /src/pages/guides/authentication/JWT/index.md
Users receive a 404 when clicking the embedded link for 'Create a public key certificate'.
 https://www.adobe.io/developer-console/docs/guides/authentication/AuthenticationOverview/ServiceAccountIntegration.md#step-2-create-a-public-key-certificate

**Comment by theManikJindal** [comment]
@kultgenj this is not fixed. Thanks for reporting the issue.
