### ISSUE TITLE
Issue in /src/pages/guides/authentication/ServerToServerAuthentication/migration.md

### ISSUE THREAD

**Issue by Saboggarapu** [AdobeDocs/adobe-dev-console#124]
The OAuth-Server-to-Server migration is successful. The credentials have changed from the service account. This is the guide used:
https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/

Following the steps outlined in the [Adobe.io](https://developers.adobetarget.com/api/#introduction) documentation, I generated a JWT access token. However, when attempting to exchange the JWT for a Bearer Access Token using the provided request:
‘curl -X POST \
 https://ims-na1.adobelogin.com/ims/exchange/jwt/?client_id=<[Adobe.IO](http://adobe.io/) API KEY>&client_secret=<[Adobe.IO](http://adobe.io/) Client Secret>&jwt_token=JWT_TOKEN’
I encountered an internal server error. A "500 Internal Server Error" indicates that there's an issue on the server side, and it's a generic error message that doesn't provide specific details about the problem. I tried it on the terminal window and Postman. Looks like an issue with the Adobe Server.
{
  "error": "internal_error",
  "error_description": "Please try again later"
}
I'm also interested in understanding whether we can manually add/modify scopes within our credentials, for ex: exchange_jwt scope

**Comment by theManikJindal** [comment]
Hi @Saboggarapu once you migrate from Service Account (JWT) to OAuth Server-to-Server credential you can no longer use the exchange JWT endpoint to generate access tokens. Please read the [OAuth Server-to-Server implementation guide](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation/) for info on how to generate access tokens.
