### ISSUE TITLE
Adobe Target: Cannot edit A/B activity created via API v3

### ISSUE THREAD

**Issue by kghateancestry** [AdobeDocs/adobe-dev-console#125]
### Expected Behaviour
I would like to edit an A/B activity in the UI created through the latest Admin APIs (v3)

### Actual Behaviour
When an activity is created through API, the option to edit is not available in the UI.

#### Steps to Reproduce
1. Create a new A/B activity using the admin API - https://developer.adobe.com/target/administer/admin-api/#tag/Activities/operation/createActivity_4_1
2. When the activity is created in Target, go to the activity from the UI console. 
3. There is no option to edit the activity. 

#### Platform and Version
Version of API: v3

**Comment by theManikJindal** [comment]
Hi @kghateancestry we are unable to answer API specific questions here. Please route this request through your regular support channels if you still need help.
