### ISSUE TITLE
Server-to-Server Auth doc confusingly links to itself

### ISSUE THREAD

**Issue by jkunz** [AdobeDocs/adobe-dev-console#132]
Issue in /src/pages/guides/authentication/ServerToServerAuthentication/implementation.md : 
It's a small thing, but the top paragraph states 
"The following guide goes over finer implementation details for OAuth Server-to-Server credentials. At the end of the guide is a list of recommended industry-standard OAuth2 libraries. **Before you proceed, we recommend you become familiar with the server to server authentication credentials in our [server to server authentication guide](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/implementation/).**"

That last link just points to the page we're currently on. I'm not sure if it's supposed to point to other documentation, or if it was copied from elsewhere, but it's a little confusing to be told "before you proceed with this documentation, review this documentation".

**Comment by theManikJindal** [comment]
Hello, thanks for pointing this out. This will be fixed soon.

**Comment by theManikJindal** [comment]
This is fixed now
