### ISSUE TITLE
Prerequisites out of date 

### ISSUE THREAD

**Issue by woter1832** [AdobeDocs/adobe-dev-console#82]
By the last commit dates, you're not maintaining this anymore, however, under the [prerequisite](https://github.com/AdobeDocs/adobe-dev-console/tree/main/samples/adobe-auth-python#prerequisites) section of the readme:

1. There's a choice of "Web app" or "Single-Page App" - Which one?
2. I cannot set the redirect URL to `https://localhost:8000`:

![image](https://user-images.githubusercontent.com/68354513/233852296-46aea58c-6004-405c-bc2c-eae1dbc78fd1.png)

Please update your documentation.

Thanks

**Comment by theManikJindal** [comment]
Hi @woter1832 thanks for pointing this out. We will fix it. Meanwhile you can use localhost:8000 as the redirect URI to unblock yourself.

**Comment by theManikJindal** [comment]
Hello, I had a chance to speak with our engineering team about it. For security reasons, we only support localhost URLs in the redirect URI pattern for now. See [documentation on redirect_uri parameter](https://developer.adobe.com/developer-console/docs/guides/authentication/UserAuthentication/IMS/#authorize-request).

<img width="1200" alt="image" src="https://github.com/AdobeDocs/adobe-dev-console/assets/4407243/b13eb6df-e6ec-470a-a468-34166189641c">

In the above example the application will have to supply the redirect_uri parameter as https://locahost:8000 when it triggers the authorize request.
